server:
  host: localhost
  port: 8080
  logger: true
  prefork: false

database:
  host: localhost
  port: 3306
  user: root
  password:
  dbname:
  migrate: false
  logger: true

jwt:
  secret: jwt-secret-key
